GENERAL:
    ALLOW_PLACED_BLOCKS: false
    REQUIRE_CORRECT_TOOL: true
LEVELING:
    EXP_BASE: 20
    EXP_GROWTH: 0.1
SKILLS:
  # ConfigGeneral level is calculated as the average of all skill levels.
  # Every level goes from 1 to 100
  MINING:
    EXP_VALUES:
      STONE: 1
      COAL_ORE: 2
      IRON_ORE: 3
      GOLD_ORE: 4
      REDSTONE_ORE: 4
      LAPIS_ORE: 5
      EMERALD_ORE: 10
      DIAMOND_ORE: 10
      NETHERRACK: 1
      NETHER_QUARTZ_ORE: 3
      NETHER_GOLD_ORE: 4
      ANCIENT_DEBRIS: 20
      END_STONE: 1
    LEVELS:
      DOUBLE_DROP_1: 5
      HASTY_PICK_1: 10
      HASTY_PICK_2: 25
      HASTY_PICK_3: 55
      HASTY_PICK_4: 80
      LUCKY_PICK_1: 15
      LUCKY_PICK_2: 35
      LUCKY_PICK_3: 60
      LUCKY_PICK_4: 85
      PICK_CRAFTING_1: 20 # HASTY PICK 1
      PICK_CRAFTING_2: 30 # HASTY PICK 2
      PICK_CRAFTING_3: 40 # SMITHY PICK 1
      PICK_CRAFTING_4: 70 # HASTY PICK 3
      PICK_CRAFTING_5: 100 # Pick of Ur
      XP_GAIN_1: 45
      ARTIFACTS_1: 50
      ARTIFACTS_2: 75
      PICK_REPAIR: 65
      PACK_1: 90
  LUMBERING:
    EXP_VALUES:
      OAK_LOG: 1
      SPRUCE_LOG: 1
      BIRCH_LOG: 1
      JUNGLE_LOG: 1
      ACACIA_LOG: 1
      DARK_OAK_LOG: 1
      CRIMSON_STEM: 2
      WARPED_STEM: 2
      MUSHROOM_STEM: 1
  DIGGING:
    EXP_VALUES:
      GRASS_BLOCK: 2
      DIRT: 1
      COARSE_DIRT: 2
      PODZOL: 3
      MYCELIUM: 5
      SAND: 1
      RED_SAND: 4
      SOUL_SAND: 3
      GRAVEL: 3
      CLAY: 5
  FARMING:
    EXP_VALUES:
      WHEAT: 2
      BEETROOTS: 2
      CARROT: 2
      POTATO: 2
      MELON: 3
      PUMPKIN: 3
      BAMBOO: 1
      COCOA: 1
      SUGAR_CANE: 1
      SWEET_BERRY_BUSH: 2
      CACTUS: 5
      KELP_PLANT: 2
      NETHER_WART_BLOCK: 3
      CHORUS_PLANT: 4
      CRIMSON_FUNGUS: 5

